### ISSUE TITLE
update to use Guard 2.0

### ISSUE THREAD

**Issue by e2** [guard/guard-coffeescript#13]

**Comment by ezekg** [comment]
What's the plan for releasing a new gem?

**Comment by e2** [comment]
@ezekg - waiting for access

@effkay - just asking again (I guess you're still on vacation): could you add me (cezary.baginski@gmail.com) and @thibaudgg (thibaud@thibaud.gg - just in case) as owners? Thanks!

**Comment by effkay** [comment]
@e2 @thibaudgg You're good to go, sorry for the delay!

**Comment by e2** [comment]
Guard::CoffeeScript 2.0.1 released!

Thanks @effkay!
