### ISSUE TITLE
Guard-Coffeescript does not restart after raising an exception

### ISSUE THREAD

**Issue by shicholas** [guard/guard-coffeescript#15]
I made a test repo at https://github.com/shicholas/guard-coffeescript-test/ and when I made the change to test incorrect coffescript (https://github.com/shicholas/guard-coffeescript-test/commit/a3f1cef3a270320357b938be8b93e4783687faaf) I noticed that Guard coffeescript would error out and when I reverted this change, Guard would not fire again.

**Comment by e2** [comment]
Fixed in 2.0.1

Thanks @shicholas for the test repo - I really appreciate it.

Let me know if you have any other issues.

**Comment by RomanKapitonov** [comment]
@e2 many thanks! works like a charm now

**Comment by shicholas** [comment]
thanks a bunch @e2! :clap:
